[tool.pyright]
typeCheckingMode = "off"

[tool.pylint.messages_control]
max-line-length = 121
disable = [
  "missing-docstring",
  "unused-argument",
  "protected-access",
  "too-few-public-methods",
  "too-many-locals",
  "too-many-instance-attributes",
  "invalid-name",
]

[tool.pylint.design]
# limiting the number of returns might discourage
# the use of guard clauses. So we increase the
# allowed number of returns from 6 to 8
max-returns = 8
